### ISSUE TITLE
recolor palette row slots UI

### ISSUE THREAD

**Issue by CL-9a** [CL-9a/RoAColorsGmlHelper#6]
- [x] Set 6 default (and minimum) rows
- [x] Button to add a row
- [x] Button to remove a row
- [x] Clicking on a swatch opens the color picker (#4)
- [x] Except on the top default row since it uses the main colors
- [x] Adapt number of color swatches from the palette? ~~tickbox for that?~~ (no tickbox since i'll add #14)

**Comment by C-L-9524085** [comment]
and delete them

**Comment by C-L-9524085** [comment]
also show 6 default rows since it's the minimum required
